# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65e524361cde71160e3e9fbaa019c6252f6199f49961b707af4535533fbf6cd92de0b071eac2225837fa5f214161e44c2a9485303903c3e440a7ee31c667857d
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
test:
  secret_key_base: 90f65e7e1a1d6def685fb0efa0a266a3648be766b95c7cecad412a5f6e4c31b35c175bb7119ec95e7b959a8a003e5fe891757a33d9113cce4125f4668c1d58f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>